---
services:
  s-ui:
    image: alireza7/s-ui
    container_name: s-ui
    hostname: "s-ui"
    mem_limit: 512m
    memswap_limit: 512m
    volumes:
      - "./db:/usr/local/s-ui/db"
      - "./cert:/root/cert"
    tty: true
    restart: unless-stopped
    ports:
      - "2095:2095"
      - "2096:2096"
    networks:
      - s-ui
    entrypoint: ["./entrypoint.sh"]
    environment:
      - PANEL_PORT=2095
      - PANEL_PATH=/app
      - SUB_PORT=2096
      - SUB_PATH=/sub

networks:
  s-ui:
    name: s_ui
    driver: bridge
  
  